// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCN1u8AGBHg_fLEz7OIJbPhBvJufnZ1iAo',
    appId: '1:8570964821:web:cbfa2647acc1cf420c7ddc',
    messagingSenderId: '8570964821',
    projectId: 'titaapp-9b3af',
    authDomain: 'titaapp-9b3af.firebaseapp.com',
    storageBucket: 'titaapp-9b3af.firebasestorage.app',
    measurementId: 'G-SLC8604EWF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9sqNJP4MIxl-qQ0vKwQjteXMAVOFlwOg',
    appId: '1:8570964821:android:ceaa9b1cadf7c9f10c7ddc',
    messagingSenderId: '8570964821',
    projectId: 'titaapp-9b3af',
    storageBucket: 'titaapp-9b3af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoFlYaL8eRWV5nt2E2mlQC7wjgRKqj5Y8',
    appId: '1:8570964821:ios:21698abf560fd4480c7ddc',
    messagingSenderId: '8570964821',
    projectId: 'titaapp-9b3af',
    storageBucket: 'titaapp-9b3af.firebasestorage.app',
    iosBundleId: 'com.example.titaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoFlYaL8eRWV5nt2E2mlQC7wjgRKqj5Y8',
    appId: '1:8570964821:ios:21698abf560fd4480c7ddc',
    messagingSenderId: '8570964821',
    projectId: 'titaapp-9b3af',
    storageBucket: 'titaapp-9b3af.firebasestorage.app',
    iosBundleId: 'com.example.titaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCN1u8AGBHg_fLEz7OIJbPhBvJufnZ1iAo',
    appId: '1:8570964821:web:4f53267452aced9b0c7ddc',
    messagingSenderId: '8570964821',
    projectId: 'titaapp-9b3af',
    authDomain: 'titaapp-9b3af.firebaseapp.com',
    storageBucket: 'titaapp-9b3af.firebasestorage.app',
    measurementId: 'G-6D51VH2J1Z',
  );
}
